package collzap.backend.enums;

public enum NotificationType {
    MATCH_FOUND,
    GROUP_MEMBER_JOINED,
    NEW_MESSAGE,
    VERIFICATION_APPROVED,
    VERIFICATION_REJECTED,
    UNMATCHED,
    DAILY_TASK_ASSIGNED,
    SOLO_TASK_REVIEWED,
    MATCHING_UNLOCKED
}
